project:
  type: book

book:
  title: "All"
  author: "Thomas Wright"
  date: "3/9/2026"
  chapters:
    - index.qmd
    - intro.qmd
    #- part: file_name.qmd
    #  chapters: 
    #    - file_name.qmd
    #- part: "Part Name" -- if just want a title not a document
    #  chapters: 
    #    - file_name.qmd
    - summary.qmd
    - references.qmd
    #appendices:
    # - file_name.qmd

bibliography: references.bib

page-navigation: true

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



